# Generated by Django 5.0.7 on 2024-08-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='country',
            new_name='about',
        ),
    ]
